### PR TITLE
support password-protected vercel deployments

### PR DESCRIPTION
**Pull request by JoshBarr**
Hey @patrickedqvist, thanks for making this library! 

I'm sure you love unsolicited PRs as much as any other maintainer 😅  Apologies in advance! 

We've been looking for a way to run our e2e tests against the preview URL for a while. We password protect all our preview deployments, so we needed a way [sign in programmtically](https://vercel.com/docs/errors#errors/bypassing-password-protection-programmatically) inside the action. 

Here's a summary of what's changed:

## Functional changes
- Adds support for a `vercel_password` input, which is used to obtain a `_vercel_jwt` cookie for browsing authenticated sites. 
- Since we're going to the trouble of parsing the JWT, we make it available as an output, so that it can passed on to e2e tests. 

## bug fixes
- Fixed an issue where the deployment notification would never resolve, if there was another non-vercel deployment running in another workflow on the same PR. We look up the deployment that's triggered by `vercel[bot]` rather than just taking the first deployment. 
- Fixed a couple of minor flow control things, where the code would keep running after `setFailure()`, which sometimes resulted in double errors 

## dev experience and CI
- Adds a prettier config
- Added a few unit tests with Jest and MockServiceWorker
- Adds a workflow for running the unit tests
- Dropped the `node_modules` from the package, in favour of compiling the project with [ncc](https://github.com/vercel/ncc). This is apparently how [GitHub build most of their actions](https://github.com/actions/hello-world-javascript-action/issues/12).

### CODE REVIEW

**Comment by patrickedqvist** [comment]
@JoshBarr Thank you so much for your contribution! 

Unsolicited PRs are more than welcome since I don't always have the time to add new features myself. I scrolled through your changes which looks good but I'm going to make a more thorough review soon.

**Comment by JoshBarr** [comment]
Thanks Patrick! Let me know if there's things I can improve, clarify or change to fit with your plans for this library, too! :) 

I've updated the `test` workflow to include code coverage reporting:

Screen Shot 2022-01-14 at 6 40 55 AM

If you re-run the workflow (it needs approval), we should get an automatic comment on the PR with our coverage metrics.

**Comment by JoshBarr** [comment]
It looks like the coverage reporting step failed. I've reverted that change for now.

**Comment by JoshBarr** [comment]
I fixed another edge case: when fetching the initial list of deployments for the PR, it's possible that the `wait-for-vercel` action gets triggered before `vercel` has reported its first deployment status. I've modified the action so that it waits for a deployment to show up from `vercel[bot]` before checking the status of it.

**Pull request merged**
