### PR TITLE
Update readme with push event support

### PR DESCRIPTION
**Pull request by vitorbal**
Hello! First of all, thank you for your work on this action! :)

After the changes in [this PR](https://github.com/patrickedqvist/wait-for-vercel-preview/pull/26), this action should now work properly for `push` events as well. That's because we now fallback to grabbing the `sha` from `github.context.sha`, which will work for `push` events!

I've updated the README to reflect this.

I also noticed that the github workflows were still referencing a `master` branch, but that branch was renamed to `main`. I pushed a commit to fix that too. Thank you!

### CODE REVIEW

**Comment by vitorbal** [comment]
@patrickedqvist :wave: just checking in if you think there's anything else I could do to help land this? Thank you!

**Comment by patrickedqvist** [comment]
@vitorbal Thanks for checking in.

Could you also update the action.yml?

**Comment by vitorbal** [comment]
@patrickedqvist done!

**Comment by vitorbal** [comment]
@patrickedqvist done!

**Pull request merged**
